### ISSUE TITLE
Extend ping exporter to contain metadata for ping targets

### ISSUE THREAD

**Issue by dansl19** [travelping/ping-exporter#4]
I would like to ask to extend the functionality of ping-exporter to include field/option with description of source and destination checked IPs.  

```pingExporter:
  enabled: true
  targets:
    - sourceV4: 10.10.10.0  [DESCRIPTION OF THIS IP, EXAMPLE :  Gy Interface ]   
      sourceV6: "::"   # Source address of ICMP requests
      pingInterval: 5s             # interval for ICMP requests
      pingTimeout: 4s              # timeout for ICMP requests
      pingTargets:                 # list of ICMP targets
        - 10.70.152.40     [DESCRIPTION OF THIS IP, EXAMPLE : MARIMBA OSS IP ]
```

Reason for this request : Provide as much information as possible about the checks, which will help to person on-call to react on failing check faster.

**Comment by mgumz** [comment]
The current output of `ping-exporter` is the /metrics endpoint and it looks like:

```
% curl http://localhost:9427/metrics
# HELP ping_loss_percent Packet loss in percent
# TYPE ping_loss_percent gauge
ping_loss_percent{ip="127.0.0.1",ip_version="4",source_ip="0.0.0.0",target="127.0.0.1"} 0
```

In the end, it looks like you want to achieve something like `ping_loss_percent` contains more labels like 'source_ip_descr="xyz"', 'target_ip_descr="uvw"'. Or, as a sample result of your proposed feature, it shall look like:

```
ping_loss_percent{ip="127.0.0.1",ip_version="4",source_ip="0.0.0.0",source_ip_descr="xyz", target="127.0.0.1",target_ip_descr="uvw"} 0
```

(see https://prometheus.io/docs/practices/naming/#labels)

Did I get your proposal right? Or are you after something else?

**Comment by dansl19** [comment]
you got it right , we need something like this 

`
ping_loss_percent{ip="127.0.0.1",ip_v
ersion="4",source_ip="0.0.0.0",source_ip_descr="xyz",` target="127.0.0.1",target_ip_descr="uvw"} 0

`

**Comment by grundrauschen** [comment]
The feature was adde as of version `0.6.0` in commit 0761436ce1649fad666fe8441facf3ac55d074df.
The changes in the configuration are breaking and documented in the README.
Please have a look if it works fine for you.
I will close this issue and reopen if parts are missing or there are bugs.
